In [1]:
import numpy as np
import sys 

#Algebra and Size
#Integers in python
sys.getsizeof(1)


28

In [2]:
#Longs
sys.getsizeof(10**100)

72

In [3]:
#Comparing with numpy size
np.dtype(int).itemsize

8

In [4]:
np.dtype(float).itemsize

8

In [5]:
#Lists
sys.getsizeof([1])

64

In [6]:
np.array([1]).nbytes

8

In [11]:
#Performance is also important
l = list(range(100000))

In [12]:
a = np.arange(100000)

In [13]:
%time np.sum(a ** 2)

CPU times: user 927 µs, sys: 61 µs, total: 988 µs
Wall time: 586 µs


333328333350000

In [10]:
%time sum([x ** 2 for x in l])

CPU times: user 50 µs, sys: 0 ns, total: 50 µs
Wall time: 52 µs


332833500

In [14]:
#Useful Numpy Functions
#random
np.random.random(size = 2)

array([0.30088862, 0.65268184])

In [15]:
np.random.normal(size = 2)

array([ 1.26280344, -1.46272322])

In [16]:
np.random.rand(2, 4)

array([[0.39817754, 0.48626551, 0.2086877 , 0.0813409 ],
       [0.92536691, 0.33939216, 0.17066401, 0.60191289]])

In [17]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [20]:
#reshape
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
#linspace
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.linspace(0, 1, 20)
#creates an array of 20 evenly spaced numbers starting at 0 and ending at 1, inclusive. The numbers
#are uniformly distributed across the interval.

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [25]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [26]:
#zeros, ones,empty
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((3, 3), dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.empty(5

SyntaxError: incomplete input (2436041397.py, line 1)

In [33]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
#identity and eye
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.eye(8, 4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k = -3)

In [ ]:
"Hello World"[6]