In [12]:
import numpy as np

#Boolean Operators
a = np.arange(4)

In [13]:
a

array([0, 1, 2, 3])

In [14]:
a[[0, -1]]

array([0, 3])

In [15]:
a[[True, False, False, True]]

array([0, 3])

In [16]:
a >= 2

array([False, False,  True,  True])

In [17]:
a[a >= 2]

array([2, 3])

In [19]:
a.mean()

1.5

In [21]:
a[a > a.mean()]

array([2, 3])

In [22]:
a[~(a > a.mean())]

array([0, 1])

In [23]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [24]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [28]:
A = np.random.randint(100, size=(3, 3))

In [29]:
A

array([[12, 77, 97],
       [20, 41, 96],
       [ 4, 51, 87]])