In [4]:
#Numpy operations
import numpy as np
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [6]:
a + 10

array([10, 11, 12, 13])

In [7]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

In [8]:
a += 100

In [9]:
a

array([100, 101, 102, 103])

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

In [ ]:
a = np.arange(4)

In [ ]:
a

In [11]:
b = np.array([10, 10, 10, 10])

In [12]:
a + b

array([110, 111, 112, 113])

In [13]:
a * b

array([1000, 1010, 1020, 1030])